= Implementazione di algoritmi paralleli su GPU per il calcolo d'indici di centralità nell'ambito dell'Analisi delle Reti Sociali
Alma Mater Studiorum · Università di Bologna
8 Aprile 2021, Corso di Laurea Triennale in Ingegneria e Scienze Informatiche
:icons: font
:toc-title: Tavola dei contenuti
:figure-caption: Figura
:version-label:
:sectnums:
:xrefstyle: short
:toc: macro
:bibtex-file: ./docs/bibliography.bib
:srcdir: ../scripts
:imagesdir: ./images
:compiler_nvidia: nvcc 11.2.142
:compiler_local: GCC 10.2.1
:hardware_local: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
:hardware_nvidia: Quadro P620 (cc 6.1 - Pascal)

'''

|=======
|Tirocinante |Riccardo Battistini · 0000873514
|Tutor didattico |Moreno Marzolla
|Laboratorio |High-Performance Computing
|Periodo di svolgimento del tirocinio |01/04/21 - 31/05/21
|=======

<<<

toc::[]

'''

== Introduzione

In questa sezione il tirocinante introduce il contesto aziendale o
di laboratorio in cui ha lavorato e spiega l’obiettivo del tirocinio.

'''

Reperimento, selezione e sintesi di articoli scientifici e loro valutazione critica.
Applicazione di tecniche di parallelizzazione nel contesto della programmazione su GPU.

== Tecnologie

In questa sezione il tirocinante elenca e commenta brevemente le
tecnologie utilizzate (linguaggi, piattaforme, sistemi operativi, ecc.).

'''

Durante il tirocinio si è sviluppata un'applicazione a linea di
comando accelerata dalla GPU per il calcolo della _betweenness centrality_,
una metrica comunemente impiegata nel campo dell'Analisi delle Reti Sociali.

Per realizzare l'applicativo sono stati impiegati i linguaggi C, {cpp} e CUDA {cpp}.
In particolare il software realizzato impiega il CUDA Toolkit cite:[cuda] e
gli standard C99 e {cpp}11. Come sistema per l'automazione dello sviluppo è stato impiegato il software multipiattaforma CMake 3.9. Git 2.3 è stato utilizzato per il controllo di versione.

Per la realizzazione della documentazione del progetto sono stati impiegati
il linguaggio di markup Asciidoc, Gnuplot 5.2 per la creazione dei grafici e
il linguaggio Bibtex per la gestione della bibliografia.

Come formati per la memorizzazione dei dati sono stati impiegati Matrix Market,
standard per la rappresentazione di matrici sparse cite:[matrix-market],
e CSV per memorizzare i risultati della valutazione delle prestazioni e della scalabilità.

Infine per verificare il funzionamento dell'applicazione sono stati impiegati degli script in Bash 4.4.2, per la raccolta dei risultati, e Python 3.8, per processare i dati ottenuti.

L'applicazione è stata sviluppata e testata solo sul sistema operativo
Ubuntu 18.04. In ogni caso il funzionamento dovrebbe essere garantito senza problemi anche su altre distribuzioni GNU/Linux, MacOS e Windows, a patto che siano soddisfatte le dipendenze.

== Attività

Questa sezione, eventualmente frazionata in sottosezioni, è quella centrale e
più corposa dell’elaborato e deve illustrare (dal punto di vista tecnico, non
necessariamente cronologico) le attività svolte durante il tirocinio. A eccezione di
eventuali esempi, non deve includere il codice sviluppato; per descrivere algoritmi si
usino piuttosto pseudo-codice e/o diagrammi di vario tipo. Per lavori di tipo progettuale
è utile includere una sintetica documentazione formale di progetto.

'''

=== Misure di centralità e betweenness

=== Algoritmo seriale di Brandes

=== Shortest Path Vertex Betweenness

=== Grafo dinamico

=== Implementazione di un algoritmo parallelo su GPU

=== Studio di scalabilità e throughput

[[omp-speedup]]
.Confronto delle prestazioni, definite in termini di speedup, della versione OpenMP con alcuni degli insiemi di dati forniti.
gnuplot::{srcdir}/figure1.plot[svg, align="center"]

== Conclusioni

In questa parte lo studente trae le conclusioni del lavoro svolto, valutando
pregi e difetti dell’esperienza e, più specificamente, riassumendo quanto
appreso.

Il software sviluppato è liberamente disponibile in un link:https://github.com/Da3dalu2/SocNetAlgsOnGPU[repository su GitHub].

[bibliography]
== Riferimenti bibliografici

bibliography::[]
